const a= {
    "location": {
        "name": "London",
        "region": "City of London, Greater London",
        "country": "United Kingdom",
        "lat": 51.5171,
        "lon": -0.1062,
        "tz_id": "Europe/London",
        "localtime_epoch": 1733573391,
        "localtime": "2024-12-07 12:09"
    },
    "current": {
        "last_updated_epoch": 1733572800,
        "last_updated": "2024-12-07 12:00",
        "temp_c": 7.2,
        "temp_f": 45.0,
        "is_day": 1,
        "condition": {
            "text": "Light rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
            "code": 1183
        },
        "wind_mph": 20.1,
        "wind_kph": 32.4,
        "wind_degree": 267,
        "wind_dir": "W",
        "pressure_mb": 989.0,
        "pressure_in": 29.21,
        "precip_mm": 1.87,
        "precip_in": 0.07,
        "humidity": 87,
        "cloud": 75,
        "feelslike_c": 2.7,
        "feelslike_f": 36.9,
        "windchill_c": 1.2,
        "windchill_f": 34.2,
        "heatindex_c": 6.0,
        "heatindex_f": 42.9,
        "dewpoint_c": 4.6,
        "dewpoint_f": 40.2,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 0.0,
        "gust_mph": 27.2,
        "gust_kph": 43.7
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2024-12-07",
                "date_epoch": 1733529600,
                "day": {
                    "maxtemp_c": 9.0,
                    "maxtemp_f": 48.1,
                    "mintemp_c": 5.7,
                    "mintemp_f": 42.3,
                    "avgtemp_c": 7.7,
                    "avgtemp_f": 45.9,
                    "maxwind_mph": 27.3,
                    "maxwind_kph": 43.9,
                    "totalprecip_mm": 9.99,
                    "totalprecip_in": 0.39,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 7.5,
                    "avgvis_miles": 4.0,
                    "avghumidity": 82,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 98,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Moderate rain",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                        "code": 1189
                    },
                    "uv": 0.0
                },
                "astro": {
                    "sunrise": "07:52 AM",
                    "sunset": "03:52 PM",
                    "moonrise": "12:22 PM",
                    "moonset": "10:34 PM",
                    "moon_phase": "Waxing Crescent",
                    "moon_illumination": 32,
                    "is_moon_up": 0,
                    "is_sun_up": 0
                },
                "hour": [
                    {
                        "time_epoch": 1733529600,
                        "time": "2024-12-07 00:00",
                        "temp_c": 12.0,
                        "temp_f": 53.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 21.0,
                        "wind_kph": 33.8,
                        "wind_degree": 197,
                        "wind_dir": "SSW",
                        "pressure_mb": 998.0,
                        "pressure_in": 29.48,
                        "precip_mm": 0.33,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 91,
                        "cloud": 100,
                        "feelslike_c": 8.9,
                        "feelslike_f": 48.0,
                        "windchill_c": 8.9,
                        "windchill_f": 48.0,
                        "heatindex_c": 12.0,
                        "heatindex_f": 53.5,
                        "dewpoint_c": 10.5,
                        "dewpoint_f": 51.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 32.4,
                        "gust_kph": 52.1,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733533200,
                        "time": "2024-12-07 01:00",
                        "temp_c": 12.8,
                        "temp_f": 55.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 19.9,
                        "wind_kph": 32.0,
                        "wind_degree": 221,
                        "wind_dir": "SW",
                        "pressure_mb": 997.0,
                        "pressure_in": 29.43,
                        "precip_mm": 0.08,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 80,
                        "cloud": 98,
                        "feelslike_c": 10.2,
                        "feelslike_f": 50.3,
                        "windchill_c": 10.2,
                        "windchill_f": 50.3,
                        "heatindex_c": 12.8,
                        "heatindex_f": 55.1,
                        "dewpoint_c": 9.6,
                        "dewpoint_f": 49.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 31.1,
                        "gust_kph": 50.1,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733536800,
                        "time": "2024-12-07 02:00",
                        "temp_c": 11.5,
                        "temp_f": 52.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 20.6,
                        "wind_kph": 33.1,
                        "wind_degree": 227,
                        "wind_dir": "SW",
                        "pressure_mb": 995.0,
                        "pressure_in": 29.39,
                        "precip_mm": 0.07,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 72,
                        "cloud": 98,
                        "feelslike_c": 8.3,
                        "feelslike_f": 47.0,
                        "windchill_c": 8.3,
                        "windchill_f": 47.0,
                        "heatindex_c": 11.5,
                        "heatindex_f": 52.7,
                        "dewpoint_c": 6.7,
                        "dewpoint_f": 44.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 30.3,
                        "gust_kph": 48.8,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733540400,
                        "time": "2024-12-07 03:00",
                        "temp_c": 10.9,
                        "temp_f": 51.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 21.5,
                        "wind_kph": 34.6,
                        "wind_degree": 231,
                        "wind_dir": "SW",
                        "pressure_mb": 995.0,
                        "pressure_in": 29.37,
                        "precip_mm": 0.01,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 67,
                        "cloud": 92,
                        "feelslike_c": 7.5,
                        "feelslike_f": 45.4,
                        "windchill_c": 7.5,
                        "windchill_f": 45.4,
                        "heatindex_c": 10.9,
                        "heatindex_f": 51.6,
                        "dewpoint_c": 5.0,
                        "dewpoint_f": 41.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 73,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 31.3,
                        "gust_kph": 50.3,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733544000,
                        "time": "2024-12-07 04:00",
                        "temp_c": 10.0,
                        "temp_f": 49.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 22.1,
                        "wind_kph": 35.6,
                        "wind_degree": 231,
                        "wind_dir": "SW",
                        "pressure_mb": 993.0,
                        "pressure_in": 29.33,
                        "precip_mm": 0.03,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 70,
                        "cloud": 100,
                        "feelslike_c": 6.2,
                        "feelslike_f": 43.1,
                        "windchill_c": 6.2,
                        "windchill_f": 43.1,
                        "heatindex_c": 10.0,
                        "heatindex_f": 49.9,
                        "dewpoint_c": 4.8,
                        "dewpoint_f": 40.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 71,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 31.8,
                        "gust_kph": 51.2,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733547600,
                        "time": "2024-12-07 05:00",
                        "temp_c": 9.8,
                        "temp_f": 49.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 23.3,
                        "wind_kph": 37.4,
                        "wind_degree": 240,
                        "wind_dir": "WSW",
                        "pressure_mb": 992.0,
                        "pressure_in": 29.3,
                        "precip_mm": 0.07,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 67,
                        "cloud": 100,
                        "feelslike_c": 5.8,
                        "feelslike_f": 42.4,
                        "windchill_c": 5.8,
                        "windchill_f": 42.4,
                        "heatindex_c": 9.8,
                        "heatindex_f": 49.6,
                        "dewpoint_c": 3.9,
                        "dewpoint_f": 39.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 32.8,
                        "gust_kph": 52.8,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733551200,
                        "time": "2024-12-07 06:00",
                        "temp_c": 9.0,
                        "temp_f": 48.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 24.6,
                        "wind_kph": 39.6,
                        "wind_degree": 236,
                        "wind_dir": "WSW",
                        "pressure_mb": 991.0,
                        "pressure_in": 29.26,
                        "precip_mm": 0.08,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 70,
                        "cloud": 100,
                        "feelslike_c": 4.6,
                        "feelslike_f": 40.3,
                        "windchill_c": 4.6,
                        "windchill_f": 40.3,
                        "heatindex_c": 9.0,
                        "heatindex_f": 48.1,
                        "dewpoint_c": 3.8,
                        "dewpoint_f": 38.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 32.8,
                        "gust_kph": 52.7,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733554800,
                        "time": "2024-12-07 07:00",
                        "temp_c": 8.0,
                        "temp_f": 46.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 24.8,
                        "wind_kph": 40.0,
                        "wind_degree": 246,
                        "wind_dir": "WSW",
                        "pressure_mb": 990.0,
                        "pressure_in": 29.23,
                        "precip_mm": 0.06,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 70,
                        "cloud": 100,
                        "feelslike_c": 3.3,
                        "feelslike_f": 38.0,
                        "windchill_c": 3.3,
                        "windchill_f": 38.0,
                        "heatindex_c": 8.0,
                        "heatindex_f": 46.4,
                        "dewpoint_c": 3.0,
                        "dewpoint_f": 37.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 32.6,
                        "gust_kph": 52.5,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733558400,
                        "time": "2024-12-07 08:00",
                        "temp_c": 7.4,
                        "temp_f": 45.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 26.8,
                        "wind_kph": 43.2,
                        "wind_degree": 250,
                        "wind_dir": "WSW",
                        "pressure_mb": 989.0,
                        "pressure_in": 29.21,
                        "precip_mm": 0.26,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 74,
                        "cloud": 100,
                        "feelslike_c": 2.4,
                        "feelslike_f": 36.2,
                        "windchill_c": 2.4,
                        "windchill_f": 36.2,
                        "heatindex_c": 7.4,
                        "heatindex_f": 45.4,
                        "dewpoint_c": 3.1,
                        "dewpoint_f": 37.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 34.5,
                        "gust_kph": 55.6,
                        "uv": 0.0,
                        "short_rad": 0.0,
                        "diff_rad": 0.0
                    },
                    {
                        "time_epoch": 1733562000,
                        "time": "2024-12-07 09:00",
                        "temp_c": 6.6,
                        "temp_f": 43.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 27.3,
                        "wind_kph": 43.9,
                        "wind_degree": 253,
                        "wind_dir": "WSW",
                        "pressure_mb": 989.0,
                        "pressure_in": 29.2,
                        "precip_mm": 1.1,
                        "precip_in": 0.04,
                        "snow_cm": 0.0,
                        "humidity": 79,
                        "cloud": 100,
                        "feelslike_c": 1.2,
                        "feelslike_f": 34.1,
                        "windchill_c": 1.2,
                        "windchill_f": 34.1,
                        "heatindex_c": 6.6,
                        "heatindex_f": 43.9,
                        "dewpoint_c": 3.3,
                        "dewpoint_f": 37.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 34.1,
                        "gust_kph": 54.8,
                        "uv": 0.0,
                        "short_rad": 1.32,
                        "diff_rad": 0.8
                    },
                    {
                        "time_epoch": 1733565600,
                        "time": "2024-12-07 10:00",
                        "temp_c": 5.7,
                        "temp_f": 42.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 26.8,
                        "wind_kph": 43.2,
                        "wind_degree": 254,
                        "wind_dir": "WSW",
                        "pressure_mb": 988.0,
                        "pressure_in": 29.19,
                        "precip_mm": 1.96,
                        "precip_in": 0.08,
                        "snow_cm": 0.0,
                        "humidity": 87,
                        "cloud": 100,
                        "feelslike_c": 0.1,
                        "feelslike_f": 32.1,
                        "windchill_c": 0.1,
                        "windchill_f": 32.1,
                        "heatindex_c": 5.7,
                        "heatindex_f": 42.3,
                        "dewpoint_c": 3.7,
                        "dewpoint_f": 38.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 34.0,
                        "gust_kph": 54.8,
                        "uv": 0.0,
                        "short_rad": 3.34,
                        "diff_rad": 2.14
                    },
                    {
                        "time_epoch": 1733569200,
                        "time": "2024-12-07 11:00",
                        "temp_c": 5.7,
                        "temp_f": 42.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 24.6,
                        "wind_kph": 39.6,
                        "wind_degree": 257,
                        "wind_dir": "WSW",
                        "pressure_mb": 988.0,
                        "pressure_in": 29.18,
                        "precip_mm": 1.14,
                        "precip_in": 0.04,
                        "snow_cm": 0.0,
                        "humidity": 88,
                        "cloud": 100,
                        "feelslike_c": 0.3,
                        "feelslike_f": 32.5,
                        "windchill_c": 0.3,
                        "windchill_f": 32.5,
                        "heatindex_c": 5.7,
                        "heatindex_f": 42.3,
                        "dewpoint_c": 4.0,
                        "dewpoint_f": 39.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 32.4,
                        "gust_kph": 52.2,
                        "uv": 0.1,
                        "short_rad": 4.36,
                        "diff_rad": 2.96
                    },
                    {
                        "time_epoch": 1733572800,
                        "time": "2024-12-07 12:00",
                        "temp_c": 7.2,
                        "temp_f": 45.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 20.1,
                        "wind_kph": 32.4,
                        "wind_degree": 267,
                        "wind_dir": "W",
                        "pressure_mb": 989.0,
                        "pressure_in": 29.21,
                        "precip_mm": 1.87,
                        "precip_in": 0.07,
                        "snow_cm": 0.0,
                        "humidity": 87,
                        "cloud": 75,
                        "feelslike_c": 1.2,
                        "feelslike_f": 34.2,
                        "windchill_c": 1.2,
                        "windchill_f": 34.2,
                        "heatindex_c": 6.0,
                        "heatindex_f": 42.9,
                        "dewpoint_c": 4.6,
                        "dewpoint_f": 40.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 27.2,
                        "gust_kph": 43.7,
                        "uv": 0.0,
                        "short_rad": 4.74,
                        "diff_rad": 3.33
                    },
                    {
                        "time_epoch": 1733576400,
                        "time": "2024-12-07 13:00",
                        "temp_c": 6.4,
                        "temp_f": 43.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 19.7,
                        "wind_kph": 31.7,
                        "wind_degree": 287,
                        "wind_dir": "WNW",
                        "pressure_mb": 988.0,
                        "pressure_in": 29.18,
                        "precip_mm": 0.31,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 87,
                        "cloud": 100,
                        "feelslike_c": 1.7,
                        "feelslike_f": 35.1,
                        "windchill_c": 1.7,
                        "windchill_f": 35.1,
                        "heatindex_c": 6.4,
                        "heatindex_f": 43.5,
                        "dewpoint_c": 4.4,
                        "dewpoint_f": 39.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 26.2,
                        "gust_kph": 42.1,
                        "uv": 0.0,
                        "short_rad": 5.36,
                        "diff_rad": 4.35
                    },
                    {
                        "time_epoch": 1733580000,
                        "time": "2024-12-07 14:00",
                        "temp_c": 6.9,
                        "temp_f": 44.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 19.7,
                        "wind_kph": 31.7,
                        "wind_degree": 301,
                        "wind_dir": "WNW",
                        "pressure_mb": 989.0,
                        "pressure_in": 29.21,
                        "precip_mm": 0.09,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 84,
                        "cloud": 100,
                        "feelslike_c": 2.4,
                        "feelslike_f": 36.4,
                        "windchill_c": 2.4,
                        "windchill_f": 36.4,
                        "heatindex_c": 6.9,
                        "heatindex_f": 44.5,
                        "dewpoint_c": 4.4,
                        "dewpoint_f": 39.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 26.8,
                        "gust_kph": 43.2,
                        "uv": 0.0,
                        "short_rad": 9.18,
                        "diff_rad": 6.43
                    },
                    {
                        "time_epoch": 1733583600,
                        "time": "2024-12-07 15:00",
                        "temp_c": 6.4,
                        "temp_f": 43.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 20.8,
                        "wind_kph": 33.5,
                        "wind_degree": 305,
                        "wind_dir": "NW",
                        "pressure_mb": 991.0,
                        "pressure_in": 29.27,
                        "precip_mm": 0.03,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 84,
                        "cloud": 100,
                        "feelslike_c": 1.6,
                        "feelslike_f": 34.9,
                        "windchill_c": 1.6,
                        "windchill_f": 34.9,
                        "heatindex_c": 6.4,
                        "heatindex_f": 43.5,
                        "dewpoint_c": 3.9,
                        "dewpoint_f": 39.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 77,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 27.6,
                        "gust_kph": 44.4,
                        "uv": 0.0,
                        "short_rad": 8.2,
                        "diff_rad": 5.67
                    },
                    {
                        "time_epoch": 1733587200,
                        "time": "2024-12-07 16:00",
                        "temp_c": 6.3,
                        "temp_f": 43.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 20.4,
                        "wind_kph": 32.8,
                        "wind_degree": 308,
                        "wind_dir": "NW",
                        "pressure_mb": 993.0,
                        "pressure_in": 29.32,
                        "precip_mm": 0.01,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 85,
                        "cloud": 100,
                        "feelslike_c": 1.5,
                        "feelslike_f": 34.6,
                        "windchill_c": 1.5,
                        "windchill_f": 34.6,
                        "heatindex_c": 6.3,
                        "heatindex_f": 43.3,
                        "dewpoint_c": 3.9,
                        "dewpoint_f": 39.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 63,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 28.1,
                        "gust_kph": 45.2,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733590800,
                        "time": "2024-12-07 17:00",
                        "temp_c": 6.3,
                        "temp_f": 43.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 20.8,
                        "wind_kph": 33.5,
                        "wind_degree": 310,
                        "wind_dir": "NW",
                        "pressure_mb": 994.0,
                        "pressure_in": 29.36,
                        "precip_mm": 0.11,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 84,
                        "cloud": 100,
                        "feelslike_c": 1.4,
                        "feelslike_f": 34.6,
                        "windchill_c": 1.4,
                        "windchill_f": 34.6,
                        "heatindex_c": 6.3,
                        "heatindex_f": 43.3,
                        "dewpoint_c": 3.9,
                        "dewpoint_f": 38.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 28.7,
                        "gust_kph": 46.3,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733594400,
                        "time": "2024-12-07 18:00",
                        "temp_c": 5.8,
                        "temp_f": 42.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 22.1,
                        "wind_kph": 35.6,
                        "wind_degree": 314,
                        "wind_dir": "NW",
                        "pressure_mb": 996.0,
                        "pressure_in": 29.4,
                        "precip_mm": 0.12,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 87,
                        "cloud": 100,
                        "feelslike_c": 0.6,
                        "feelslike_f": 33.1,
                        "windchill_c": 0.6,
                        "windchill_f": 33.1,
                        "heatindex_c": 5.8,
                        "heatindex_f": 42.4,
                        "dewpoint_c": 3.7,
                        "dewpoint_f": 38.7,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 30.2,
                        "gust_kph": 48.6,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733598000,
                        "time": "2024-12-07 19:00",
                        "temp_c": 6.2,
                        "temp_f": 43.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                            "code": 1183
                        },
                        "wind_mph": 22.1,
                        "wind_kph": 35.6,
                        "wind_degree": 319,
                        "wind_dir": "NW",
                        "pressure_mb": 997.0,
                        "pressure_in": 29.43,
                        "precip_mm": 1.12,
                        "precip_in": 0.04,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 1.2,
                        "feelslike_f": 34.2,
                        "windchill_c": 1.2,
                        "windchill_f": 34.2,
                        "heatindex_c": 6.2,
                        "heatindex_f": 43.2,
                        "dewpoint_c": 4.6,
                        "dewpoint_f": 40.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 31.1,
                        "gust_kph": 50.1,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733601600,
                        "time": "2024-12-07 20:00",
                        "temp_c": 6.1,
                        "temp_f": 42.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 22.1,
                        "wind_kph": 35.6,
                        "wind_degree": 319,
                        "wind_dir": "NW",
                        "pressure_mb": 998.0,
                        "pressure_in": 29.47,
                        "precip_mm": 0.38,
                        "precip_in": 0.02,
                        "snow_cm": 0.0,
                        "humidity": 90,
                        "cloud": 100,
                        "feelslike_c": 1.0,
                        "feelslike_f": 33.9,
                        "windchill_c": 1.0,
                        "windchill_f": 33.9,
                        "heatindex_c": 6.1,
                        "heatindex_f": 42.9,
                        "dewpoint_c": 4.5,
                        "dewpoint_f": 40.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 30.8,
                        "gust_kph": 49.5,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733605200,
                        "time": "2024-12-07 21:00",
                        "temp_c": 6.0,
                        "temp_f": 42.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 21.7,
                        "wind_kph": 34.9,
                        "wind_degree": 320,
                        "wind_dir": "NW",
                        "pressure_mb": 999.0,
                        "pressure_in": 29.5,
                        "precip_mm": 0.36,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 1.0,
                        "feelslike_f": 33.7,
                        "windchill_c": 1.0,
                        "windchill_f": 33.7,
                        "heatindex_c": 6.0,
                        "heatindex_f": 42.8,
                        "dewpoint_c": 4.4,
                        "dewpoint_f": 39.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 30.2,
                        "gust_kph": 48.5,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733608800,
                        "time": "2024-12-07 22:00",
                        "temp_c": 6.5,
                        "temp_f": 43.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 21.7,
                        "wind_kph": 34.9,
                        "wind_degree": 321,
                        "wind_dir": "NW",
                        "pressure_mb": 1000.0,
                        "pressure_in": 29.53,
                        "precip_mm": 0.16,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 85,
                        "cloud": 100,
                        "feelslike_c": 1.7,
                        "feelslike_f": 35.0,
                        "windchill_c": 1.7,
                        "windchill_f": 35.0,
                        "heatindex_c": 6.5,
                        "heatindex_f": 43.7,
                        "dewpoint_c": 4.2,
                        "dewpoint_f": 39.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 30.6,
                        "gust_kph": 49.2,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    },
                    {
                        "time_epoch": 1733612400,
                        "time": "2024-12-07 23:00",
                        "temp_c": 6.7,
                        "temp_f": 44.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Light drizzle",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 22.1,
                        "wind_kph": 35.6,
                        "wind_degree": 331,
                        "wind_dir": "NNW",
                        "pressure_mb": 1001.0,
                        "pressure_in": 29.56,
                        "precip_mm": 0.24,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 88,
                        "cloud": 100,
                        "feelslike_c": 1.8,
                        "feelslike_f": 35.3,
                        "windchill_c": 1.8,
                        "windchill_f": 35.3,
                        "heatindex_c": 6.7,
                        "heatindex_f": 44.0,
                        "dewpoint_c": 4.9,
                        "dewpoint_f": 40.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 31.1,
                        "gust_kph": 50.1,
                        "uv": 0,
                        "short_rad": 0,
                        "diff_rad": 0
                    }
                ]
            }
        ]
    }
}


  {/* <Image
        source={require("../assets/images/bg.png")}
        style={tw`absolute h-full w-full`}
      /> */}


      {/*<View style={tw`flex-row justify-center`}>
              <Image
                source={weatherImages[current?.condition?.text]}
                style={tw`w-46 h-46`}
              />
            </View>
            
            <View style={tw`space-y-2`}>
              <Text style={tw`text-center font-bold text-white text-6xl ml-5`}>
                {current?.temp_c}&#176;
              </Text>
              <Text style={tw`text-center text-white text-xl tracking widest`}>
                {current?.condition?.text}
              </Text>
            </View> */
            


{/* <View style={tw`mb-2 space-y-3`}>
              <View style={tw`flex-row items-center mx-5 space-x-2`}>
                <CalendarDaysIcon size="22" color="white" />
                <Text style={tw`text-white text-base`}>Daily Forecast</Text>
              </View>
              <ScrollView
                horizontal
                contentContainerStyle={{ paddingHorizontal: 15 }}
                showsHorizontalScrollIndicator={false}
              >
                {weather?.forecast?.forecastday?.map((item, index) => {
                  let date = new Date(item.date);
                  let options = { weekday: "long" };
                  let dayName = date.toLocaleDateString("en-US", options);
                  dayName = dayName.split(",")[0];

                  return (
                    <View
                      key={index}
                      style={[
                        tw`flex justify-center items-center w-24 rounded-3xl py-3`,
                        { backgroundColor: theme.bgWhite(0.15) },
                        { marginVertical: 8 },
                      ]}
                    >
                      <Image
                        source={weatherImages[item?.day?.condition?.text]}
                        style={tw`h-11 w-11`}
                      />
                      <Text style={tw`text-white`}>{dayName}</Text>
                      <Text style={tw`text-white font-semibold text-xl`}>
                        {item?.day?.avgtemp_c}&#176;
                      </Text>
                    </View>
                  );
                })}
              </ScrollView>
            </View> */}